name: Pull Request

on: pull_request

jobs:

  build:
    name: Build & test
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v1

    - name: Set up Node 12
      uses: actions/setup-node@v1
      with:
        node-version: 12.x

    - name: npm install, build and test
      run: |
        printenv | sort
        # npm install
        # npm run build --if-present
        # npm test
      env:
        CI: true
